providers:
  - airtap-sauce

browsers:
  - name: chrome
  - name: firefox
  - name: safari
  - name: edge

presets:
  local:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
      - name: webkit
